### ISSUE TITLE
Select start pose option

### ISSUE THREAD

**Issue by MarcM0** [open-navigation/opennav_coverage#64]
I have done some visualization of the planned paths. It seems the path starts at an arbitrary point near the left of the polygon, (not the corner of the polygon where the bot is). Is there a way to control this? If not, is there a way to get the start pose before path execution starts so that we can navigate to it?

**Comment by SteveMacenski** [comment]
An image of what you mean would be helpful and detail about which node you're using. The paths of the field now (not row node) should start at one of the corners of the field, minus the headlands and the tool's radius. So there are different variant options. 

v1.X in F2C includes the ability to modify the `variant` to use of those options in the API [1], however, there's not really a way to know which is which. So you'd basically just have to guess and check or generate all possible variants and then sort it out yourself as to which you want to use. For that reason, I chose not to expose that feature since it wasn't knowable beforehand & you could get the same effect just by ordering the points differently in your input file (i.e. roll the points' positions in the inputs). 

But, I did think to myself someone might eventually want that feature, so I didn't do anything that prevents a contributor from adding in which `variant` to use in the request field and propagating it to the route planner of choice. Or I suppose we could modify the request to add an option for `generate_all_variants` and return a vector of fields to choose from. 

[1] https://github.com/Fields2Cover/Fields2Cover/blob/v1.2.0/include/fields2cover/route_planning/single_cell_swaths_order_base.h#L22

> is there a way to get the start pose before path execution starts so that we can navigate to it?

Yeah! Look at the path and take its first point `path.poses[0].pose.position` and navigate there with Nav2 before then sending the rest of the plan.

**Comment by MarcM0** [comment]
Thanks for the reply, I am essentially using the demo, [https://github.com/open-navigation/opennav_coverage/tree/iron/opennav_coverage_demo](url).

> Yeah! Look at the path and take its first point path.poses[0].pose.position and navigate there with Nav2 before then sending the rest of the plan. 
I mean through the python interface. All I see is 
```
goal_msg = NavigateCompleteCoverage.Goal()
goal_msg.frame_id = frame_id
goal_msg.polygons.append(self.toPolygon(field))
self.coverage_client.send_goal_async(goal_msg, self._feedbackCallback)
```
 Am I supposed to use a compute message first? If so, then how do I run the computed path?

> get the same effect just by ordering the points differently in your input file (i.e. roll the points' positions in the inputs).
I tried rotating the input array, but no matter what is starts at the point with the lowest x value.

**Comment by SteveMacenski** [comment]
You'd need to create the appropriate behavior tree to do that - that's the power of Nav2 to allow you to modify the navigation logic to enable something like Navigating for Coverage in the first place - but it should be straight forward for what you need. Have a sequence that is: Plan a route stored in `plan` -> send the first point in `plan` to navigation as a `goal` -> continue with the rest of the BT. This is the current BT [1], its really trivial for demonstration purposes. 

You'll want to / need to extend it to your particular application desires - I'd love to add a new BT in that does what we discussed once you've put it together. I'm happy to merge that PR so that others can have that as well! 

[1] https://github.com/open-navigation/opennav_coverage/blob/main/opennav_coverage_bt/behavior_trees/navigate_w_basic_complete_coverage.xml

**Comment by MarcM0** [comment]
I see. I'm not very familiar with behavior trees. I tried setting up 2 navigators.
navigators: ['navigate_complete_coverage',"navigate_to_pose"]
but I'm not sure how to make a behavior tree that is compatible with both. Here is what I currently have, but I get an error saying I can't open it
```
<root main_tree_to_execute="MainTree">
  <BehaviorTree ID="MainTree">
    <RateController hz="0.0000001"> <!-- once, for demo -->
      <Sequence name="NavigateWithoutReplanning">
        <!-- May use:
         'polygons="{field_polygon}" polygons_frame_id="{polygon_frame_id}"' if set polygon via NavigateCompleteCoverage
         or file_field="{field_filepath}" if setting polygon file via NavigateCompleteCoverage -->
        <ComputeCoveragePath nav_path="{path}" polygons="{field_polygon}" polygons_frame_id="{polygon_frame_id}" error_code_id="{compute_coverage_error_code}"/>
        <ComputePathToPose goal="{path.poses[0].pose.position}" path="{pathToStart}" planner_id="{selected_planner}" error_code_id="{compute_path_error_code}"/>
        <FollowPath path="{pathToStart}" controller_id="FollowPath" error_code_id="{follow_path_error_code}"/>
        <FollowPath path="{path}" controller_id="FollowPath" error_code_id="{follow_path_error_code}"/>
      </Sequence>
    </RateController>
  </BehaviorTree>
</root>
```

**Comment by MarcM0** [comment]
Wait, it does work, but {path.poses[0].pose.position} is the pose of the robot. Its not the edge of the swaths

**Comment by SteveMacenski** [comment]
That generally look about right! 

Is the goal at either of those coordinates? Might be worth printing some out. What's the global frame and is that in your TF tree? Its possible that the `path.poses[0]` doesn't have its `header` populated, so you'd have to add that from the `path.header`. It might be worth creating a BT node to take in the `{path}` and return a `{goal}` which is `path.poses[0]` with the `header` populated. I think that would actually be a general purpose node worth of adding directly into Nav2!

I'm surprised that you could get `{path.poses[0]}` to work -- but its also possible that it actually doesn't work and its just populating an empty `PoseStamped()` which is why you see the coordinates `(0.00, 0.00)` and unable to transform since the frame/stamp would also be empty string / `0`.

**Comment by MarcM0** [comment]
Ya if I input any nonsense in that field I get 0,0. So its not working

**Comment by SteveMacenski** [comment]
Got it - a new BT node for that should be easy. Here's an example: https://github.com/ros-navigation/navigation2/blob/main/nav2_behavior_tree/plugins/action/remove_passed_goals_action.cpp the "work" parts of it are different, but shows how to write the BT node and get/set the input and output ports with a path

**Comment by MarcM0** [comment]
So I got it all working, although if the start point is too far, I get the following error. Any idea on how to fix it? I assume its a config thing on my side. `GridBased plugin failed to plan from (0.00, -0.01) to (-105.92, 39.25): "Goal Coordinates of(-105.918845, 39.251424) was outside bounds"`

**Comment by SteveMacenski** [comment]
I assume outside the bounds of the costmap? You just need to set that size appropriately for the field you’re in

**Comment by MarcM0** [comment]
Thanks. I guess once the pull requests are merged we can close the issue

**Comment by SteveMacenski** [comment]
These look great! Merged! Thanks for the contributions!

**Comment by sys-met** [comment]
ubuntu 22 ros2 humble
I get an error when running the navigate_w_basic_complete_coverage_nav_to_start.xml code in ros2. The cpp and hpp of the plugin are available in navigation2, but I get the following error
`[component_container_isolated-1] [INFO] [1730890680.579976100] [bt_navigator]: Activating
[component_container_isolated-1] [ERROR] [1730890680.581172489] [bt_navigator]: Exception when loading BT: Error at line 22: -> Node not recognized: GetPoseFromPath
[component_container_isolated-1] [ERROR] [1730890680.581282125] [bt_navigator]: Error loading XML file: /workspaces/isaac_ros-dev/install/opennav_coverage_bt/share/opennav_coverage_bt/behavior_trees/navigate_w_basic_complete_coverage.xml
[component_container_isolated-1] [ERROR] [1730890680.583515698] [lifecycle_manager_navigation]: Failed to change state for node: bt_navigator
[component_container_isolated-1] [ERROR] [1730890680.583599412] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.
[demo_coverage-2] Getting bt_navigator state...
[demo_coverage-2] Result of get_state: inactive
`
bt_navigator:
`bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    # 'default_coverage_bt_xml' uses defaults:
    # opennav_coverage_bt/behavior_tree/navigate_w_basic_complete_coverage.xml
    default_coverage_bt_xml: $(find-pkg-share opennav_coverage_bt)/behavior_trees/navigate_w_basic_complete_coverage.xml
    navigators: ['navigate_complete_coverage']
    navigate_complete_coverage:
      plugin: "opennav_coverage_navigator/CoverageNavigator"
    error_code_names: ["compute_path_error_code", "follow_path_error_code", "compute_coverage_error_code"]
    plugin_lib_names:
      - nav2_follow_path_action_bt_node
      - nav2_rate_controller_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - opennav_compute_complete_coverage_action_bt_node
      - opennav_cancel_complete_coverage_action_bt_node`
    
navigate_w_basic_complete_coverage.xml:
`<root main_tree_to_execute="MainTree">
  <BehaviorTree ID="MainTree">
    <RateController hz="0.0000001"> 
      <Sequence name="NavigateWithoutReplanning">
        
        <ComputeCoveragePath nav_path="{path}" polygons="{field_polygon}" polygons_frame_id="{polygon_frame_id}" error_code_id="{compute_coverage_error_code}"/>
        <GetPoseFromPath path="{path}" pose="{start_pose}" index="0" />
        <ComputePathToPose goal="{start_pose}" path="{path_to_start}" planner_id="GridBased" error_code_id="{compute_path_error_code}"/>
        <FollowPath path="{path_to_start}" controller_id="FollowPath" error_code_id="{follow_path_error_code}"/>
        <FollowPath path="{path}" controller_id="FollowPath"/>
      </Sequence>
    </RateController>
  </BehaviorTree>
</root>`
